<!DOCTYPE chine [
    <!ELEMENT chine (employes, postes, contratsDureeIndeterminee, departements, formations, seFormes, performances, absences)>
    <!ELEMENT employes (employe+)>
    <!ELEMENT employe (nom, prenom, telephone, adresse, dateDeNaissance, diplome)>
    <!ATTLIST   employe idEmploye ID #REQUIRED
                idDepartement IDREF #REQUIRED
                idPoste IDREF #REQUIRED>
    <!ELEMENT nom (#PCDATA)>
    <!ELEMENT prenom (#PCDATA)>
    <!ELEMENT telephone (#PCDATA)>
    <!ELEMENT adresse (#PCDATA)>
    <!ELEMENT dateDeNaissance (#PCDATA)>
    <!ELEMENT diplome (#PCDATA)>

    <!ELEMENT postes (poste+)>
    <!ELEMENT poste (libelle, nombreHeuresParSemaine, occupation, salaireBase)>
    <!ATTLIST poste idPoste ID #REQUIRED>
    <!ELEMENT libelle (#PCDATA)>
    <!ELEMENT nombreHeuresParSemaine (#PCDATA)>
    <!ELEMENT occupation (#PCDATA)>
    <!ELEMENT salaireBase (#PCDATA)>

    <!ELEMENT contratsDureeIndeterminee (contrat+)>
    <!ELEMENT contrat (dateDebutContrat, numeroContrat, salaire)>
    <!ATTLIST   contrat idContrat ID #REQUIRED
                idEmploye IDREF #REQUIRED>
    <!ELEMENT dateDebutContrat (#PCDATA)>
    <!ELEMENT numeroContrat (#PCDATA)>
    <!ELEMENT salaire (#PCDATA)>

    <!ELEMENT departements (departement+)>
    <!ELEMENT departement (nomDepartement, pays)>
    <!ATTLIST departement idDepartement ID #REQUIRED>
    <!ELEMENT nomDepartement (#PCDATA)>
    <!ELEMENT pays (#PCDATA)>

    <!ELEMENT formations (formation+)>
    <!ELEMENT formation (typeFormation, coutFormation)>
    <!ATTLIST formation idFormation ID #REQUIRED>
    <!ELEMENT typeFormation (#PCDATA)>
    <!ELEMENT coutFormation (#PCDATA)>

    <!ELEMENT seFormes (seForme+)>
    <!ELEMENT seForme (DateDebutFormation)>
    <!ATTLIST seForme   idSeforme ID #REQUIRED
                        idFormation IDREF #REQUIRED
                        idEmploye IDREF #REQUIRED>
    <!ELEMENT DateDebutFormation (#PCDATA)>

    <!ELEMENT performances (performance+)>
    <!ELEMENT performance (notePerformance, datePerformance)>
    <!ATTLIST performance   idPerformance ID #REQUIRED
                            idEmploye IDREF #REQUIRED>
    <!ELEMENT notePerformance (#PCDATA)>
    <!ELEMENT datePerformance (#PCDATA)>

    <!ELEMENT absences (absence+)>
    <!ELEMENT absence (motifAbsence, nombreDeJours, dateAbsence)>
    <!ATTLIST absence    idAbence ID #REQUIRED
                         idEmploye IDREF #REQUIRED>
    <!ELEMENT motifAbsence (#PCDATA)>
    <!ELEMENT nombreDeJours (#PCDATA)>
    <!ELEMENT dateAbsence (#PCDATA)>
    ]>
<chine>
    <employes>
        <employe idEmploye="8" idDepartement="4" idPoste="4">
            <nom>Li</nom>
            <prenom>Wei</prenom>
            <telephone>+86 136 5678 1234</telephone>
            <adresse>No. 678, Lane 18, Hongkou District, Shanghai, China</adresse>
            <dateDeNaissance>1993-09-05</dateDeNaissance>
            <diplome>BTS</diplome>
        </employe>
        <employe idEmploye="9"  idDepartement="2" idPoste="2">
            <nom>Zhang</nom>
            <prenom>Yan</prenom>
            <telephone>+86 135 9876 5432</telephone>
            <adresse>No. 456, Lane 7, Yangpu District, Shanghai, China</adresse>
            <dateDeNaissance>1991-12-18</dateDeNaissance>
            <diplome>Licence</diplome>
        </employe>
        <employe idEmploye="10" idDepartement="1" idPoste="1">
            <nom>Chen</nom>
            <prenom>Xia</prenom>
            <telephone>+86 185 8765 4321</telephone>
            <adresse>No. 789, Lane 12, Jing'an District, Shanghai, China</adresse>
            <dateDeNaissance>1989-02-27</dateDeNaissance>
            <diplome>Master</diplome>
        </employe>
        <employe idEmploye="11" idDepartement="1" idPoste="5">
            <nom>Liu</nom>
            <prenom>Yang</prenom>
            <telephone>+86 138 7654 3210</telephone>
            <adresse>No. 234, Lane 9, Putuo District, Shanghai, China</adresse>
            <dateDeNaissance>1995-06-20</dateDeNaissance>
            <diplome>BTS</diplome>
        </employe>
        <employe idEmploye="12" idDepartement="3" idPoste="7">
            <nom>Wang</nom>
            <prenom>Xiao</prenom>
            <telephone>13761234567</telephone>
            <adresse>Shanghai, Chine</adresse>
            <dateDeNaissance>1995-05-12</dateDeNaissance>
            <diplome>licence</diplome>
        </employe>
    </employes>

    <postes>
        <poste idPoste="1">
            <libelle>Promoteur de vente</libelle>
            <nombreHeuresParSemaine>35</nombreHeuresParSemaine>
            <occupation>true</occupation>
            <salaireBase>1950</salaireBase>
        </poste>

        <poste idPoste="5">
            <libelle>Directeur des opérations</libelle>
            <nombreHeuresParSemaine>40</nombreHeuresParSemaine>
            <occupation>true</occupation>
            <salaireBase>1900</salaireBase>
        </poste>

        <poste idPoste="9">
            <libelle>Responsable de la chaîne logistique</libelle>
            <nombreHeuresParSemaine>35</nombreHeuresParSemaine>
            <occupation>true</occupation>
            <salaireBase>2300</salaireBase>
        </poste>

        <poste idPoste="13">
            <libelle>Responsable de la qualité</libelle>
            <nombreHeuresParSemaine>35</nombreHeuresParSemaine>
            <occupation>true</occupation>
            <salaireBase>2250</salaireBase>
        </poste>

        <poste idPoste="17">
            <libelle>Chargé de la planification</libelle>
            <nombreHeuresParSemaine>35</nombreHeuresParSemaine>
            <occupation>false</occupation>
            <salaireBase>2550</salaireBase>
        </poste>
        <poste idPoste="2">
            <libelle>Directeur des ressources humaines</libelle>
            <nombreHeuresParSemaine>40</nombreHeuresParSemaine>
            <occupation>true</occupation>
            <salaireBase>1960</salaireBase>
        </poste>

        <poste idPoste="6">
            <libelle>Responsable relations sociales</libelle>
            <nombreHeuresParSemaine>35</nombreHeuresParSemaine>
            <occupation>true</occupation>
            <salaireBase>2600</salaireBase>
        </poste>

        <poste idPoste="10">
            <libelle>Chargé de formation</libelle>
            <nombreHeuresParSemaine>35</nombreHeuresParSemaine>
            <occupation>true</occupation>
            <salaireBase>2450</salaireBase>
        </poste>

        <poste idPoste="14">
            <libelle>Chargé de recrutement</libelle>
            <nombreHeuresParSemaine>35</nombreHeuresParSemaine>
            <occupation>false</occupation>
            <salaireBase>2300</salaireBase>
        </poste>

        <poste idPoste="18">
            <libelle>Responsable des ressources humaines</libelle>
            <nombreHeuresParSemaine>40</nombreHeuresParSemaine>
            <occupation>false</occupation>
            <salaireBase>2750</salaireBase>
        </poste>

        <poste idPoste="3">
            <libelle>Ingénieur logiciel</libelle>
            <nombreHeuresParSemaine>40</nombreHeuresParSemaine>
            <occupation>true</occupation>
            <salaireBase>2130</salaireBase>
        </poste>

        <poste idPoste="11">
            <libelle>Chef de projet informatique</libelle>
            <nombreHeuresParSemaine>35</nombreHeuresParSemaine>
            <occupation>true</occupation>
            <salaireBase>1900</salaireBase>
        </poste>
        <poste idPoste="15">
            <libelle>Responsable de la sécurité informatique</libelle>
            <nombreHeuresParSemaine>40</nombreHeuresParSemaine>
            <occupation>false</occupation>
            <salaireBase>2100</salaireBase>
        </poste>
        <poste idPoste="19">
            <libelle>Spécialiste en infrastructure informatique</libelle>
            <nombreHeuresParSemaine>35</nombreHeuresParSemaine>
            <occupation>false</occupation>
            <salaireBase>2250</salaireBase>
        </poste>
        <poste idPoste="4">
            <libelle>Gestionnaire de paie</libelle>
            <nombreHeuresParSemaine>35</nombreHeuresParSemaine>
            <occupation>true</occupation>
            <salaireBase>2230</salaireBase>
        </poste>
        <poste idPoste="8">
            <libelle>Directeur financier</libelle>
            <nombreHeuresParSemaine>40</nombreHeuresParSemaine>
            <occupation>false</occupation>
            <salaireBase>2100</salaireBase>
        </poste>
        <poste idPoste="12">
            <libelle>Contrôleur de gestion</libelle>
            <nombreHeuresParSemaine>35</nombreHeuresParSemaine>
            <occupation>false</occupation>
            <salaireBase>2000</salaireBase>
        </poste>

        <poste idPoste="16">
            <libelle>Comptable</libelle>
            <nombreHeuresParSemaine>35</nombreHeuresParSemaine>
            <occupation>true</occupation>
            <salaireBase>2500</salaireBase>
        </poste>

        <poste idPoste="20">
            <libelle>Controleur financier</libelle>
            <nombreHeuresParSemaine>35</nombreHeuresParSemaine>
            <occupation>false</occupation>
            <salaireBase>2550</salaireBase>
        </poste>
    </postes>
    <contratsDureeIndeterminee>
        <contrat idContrat="1" idEmploye="1">
            <dateDebutContrat>2021-01-01</dateDebutContrat>
            <numeroContrat>12001</numeroContrat>
            <salaire>3575</salaire>
        </contrat>
        <contrat idContrat="2" idEmploye="2">
            <dateDebutContrat>2021-01-02</dateDebutContrat>
            <numeroContrat>12002</numeroContrat>
            <salaire>2250</salaire>
        </contrat>
        <contrat idContrat="3" idEmploye="3">
            <dateDebutContrat>2021-01-04</dateDebutContrat>
            <numeroContrat>12003</numeroContrat>
            <salaire>4110</salaire>
        </contrat>
        <contrat idContrat="4" idEmploye="4">
            <dateDebutContrat>2021-01-04</dateDebutContrat>
            <numeroContrat>12004</numeroContrat>
            <salaire>3255</salaire>
        </contrat>
        <contrat idContrat="5" idEmploye="5">
            <dateDebutContrat>2021-01-06</dateDebutContrat>
            <numeroContrat>12005</numeroContrat>
            <salaire>2350</salaire>
        </contrat>
        <contrat idContrat="6" idEmploye="6">
            <dateDebutContrat>2021-01-06</dateDebutContrat>
            <numeroContrat>12006</numeroContrat>
            <salaire>3820</salaire>
        </contrat>
        <contrat idContrat="7" idEmploye="7">
            <dateDebutContrat>2021-01-07</dateDebutContrat>
            <numeroContrat>12007</numeroContrat>
            <salaire>3520</salaire>
        </contrat>
        <contrat idContrat="8" idEmploye="8">
            <dateDebutContrat>2021-01-08</dateDebutContrat>
            <numeroContrat>12008</numeroContrat>
            <salaire>3300</salaire>
        </contrat>
        <contrat idContrat="9" idEmploye="9">
            <dateDebutContrat>2021-01-08</dateDebutContrat>
            <numeroContrat>12009</numeroContrat>
            <salaire>4050</salaire>
        </contrat>
        <contrat idContrat="10" idEmploye="10">
            <dateDebutContrat>2021-02-08</dateDebutContrat>
            <numeroContrat>12011</numeroContrat>
            <salaire>4350</salaire>
        </contrat>
        <contrat idContrat="11" idEmploye="11">
            <dateDebutContrat>2022-01-01</dateDebutContrat>
            <numeroContrat>12012</numeroContrat>
            <salaire>3350</salaire>
        </contrat>
        <contrat idContrat="12" idEmploye="12">
            <dateDebutContrat>2022-01-15</dateDebutContrat>
            <numeroContrat>12013</numeroContrat>
            <salaire>2200</salaire>
        </contrat>
    </contratsDureeIndeterminee>
    <departements>
        <departement idDepartement="1">
            <nomDepartement>Ventes et marketing</nomDepartement>
            <pays>Chine</pays>
        </departement>
        <departement idDepartement="2">
            <nomDepartement>Ressources humaines</nomDepartement>
            <pays>Chine</pays>
        </departement>
        <departement idDepartement="3">
            <nomDepartement>IT</nomDepartement>
            <pays>Chine</pays>
        </departement>
        <departement idDepartement="4">
            <nomDepartement>Finance</nomDepartement>
            <pays>Chine</pays>
        </departement>
    </departements>
    <formations>
        <formation idFormation="1">
            <typeFormation>Formation en vente et négociation</typeFormation>
            <coutFormation>1000</coutFormation>
        </formation>
        <formation idFormation="2">
            <typeFormation>Formation en marketing digital</typeFormation>
            <coutFormation>1200</coutFormation>
        </formation>
        <formation idFormation="3">
            <typeFormation>Formation en communication interne</typeFormation>
            <coutFormation>1300</coutFormation>
        </formation>
        <formation idFormation="4">
            <typeFormation>Formation en recrutement</typeFormation>
            <coutFormation>1150</coutFormation>
        </formation>
        <formation idFormation="5">
            <typeFormation>Formation en gestion des ressources humaines</typeFormation>
            <coutFormation>1300</coutFormation>
        </formation>
        <formation idFormation="6">
            <typeFormation>Formation en comptabilité</typeFormation>
            <coutFormation>1450</coutFormation>
        </formation>
        <formation idFormation="7">
            <typeFormation>Formation en gestion financière</typeFormation>
            <coutFormation>800</coutFormation>
        </formation>
        <formation idFormation="8">
            <typeFormation>Formation en sécurité informatique</typeFormation>
            <coutFormation>700</coutFormation>
        </formation>
        <formation idFormation="9">
            <typeFormation>Formation en CISCO CCNA</typeFormation>
            <coutFormation>900</coutFormation>
        </formation>
        <formation idFormation="10">
            <typeFormation>Formation en gestion de projet</typeFormation>
            <coutFormation>500</coutFormation>
        </formation>
        <formation idFormation="11">
            <typeFormation>Formation en Langue anglaise</typeFormation>
            <coutFormation>450</coutFormation>
        </formation>
    </formations>
    <seFormes>
        <seForme idSeforme="1" idFormation="11" idEmploye="7">
            <DateDebutFormation>2022-12-20</DateDebutFormation>
        </seForme>
    </seFormes>
    <performances>
        <performance idPerformance="1" idEmploye="1">
            <notePerformance>12</notePerformance>
            <datePerformance>2021-12-01</datePerformance>
        </performance>
        <performance idPerformance="2" idEmploye="2">
            <notePerformance>10</notePerformance>
            <datePerformance>2021-12-02</datePerformance>
        </performance>
        <performance idPerformance="3" idEmploye="3">
            <notePerformance>12</notePerformance>
            <datePerformance>2021-12-03</datePerformance>
        </performance>
        <performance idPerformance="4" idEmploye="4">
            <notePerformance>14</notePerformance>
            <datePerformance>2021-12-04</datePerformance>
        </performance>
        <performance idPerformance="5" idEmploye="5">
            <notePerformance>12</notePerformance>
            <datePerformance>2021-12-05</datePerformance>
        </performance>
        <performance idPerformance="6" idEmploye="6">
            <notePerformance>14</notePerformance>
            <datePerformance>2021-12-06</datePerformance>
        </performance>
        <performance idPerformance="7" idEmploye="7">
            <notePerformance>17</notePerformance>
            <datePerformance>2021-12-07</datePerformance>
        </performance>
        <performance idPerformance="8" idEmploye="8">
            <notePerformance>19</notePerformance>
            <datePerformance>2021-12-08</datePerformance>
        </performance>
        <performance idPerformance="9" idEmploye="9">
            <notePerformance>13</notePerformance>
            <datePerformance>2021-12-09</datePerformance>
        </performance>
        <performance idPerformance="10" idEmploye="10">
            <notePerformance>11</notePerformance>
            <datePerformance>2021-12-10</datePerformance>
        </performance>

        <performance idPerformance="21" idEmploye="1">
            <notePerformance>15</notePerformance>
            <datePerformance>2022-12-01</datePerformance>
        </performance>
        <performance idPerformance="22" idEmploye="2">
            <notePerformance>13</notePerformance>
            <datePerformance>2022-12-02</datePerformance>
        </performance>
        <performance idPerformance="23" idEmploye="3">
            <notePerformance>13</notePerformance>
            <datePerformance>2022-12-03</datePerformance>
        </performance>
        <performance idPerformance="24" idEmploye="4">
            <notePerformance>17</notePerformance>
            <datePerformance>2022-12-04</datePerformance>
        </performance>
        <performance idPerformance="25" idEmploye="5">
            <notePerformance>16</notePerformance>
            <datePerformance>2022-12-05</datePerformance>
        </performance>
        <performance idPerformance="26" idEmploye="6">
            <notePerformance>14</notePerformance>
            <datePerformance>2022-12-06</datePerformance>
        </performance>
        <performance idPerformance="27" idEmploye="7">
            <notePerformance>15</notePerformance>
            <datePerformance>2022-12-07</datePerformance>
        </performance>
        <performance idPerformance="28" idEmploye="8">
            <notePerformance>19</notePerformance>
            <datePerformance>2022-12-08</datePerformance>
        </performance>
        <performance idPerformance="29" idEmploye="9">
            <notePerformance>11</notePerformance>
            <datePerformance>2022-12-09</datePerformance>
        </performance>
        <performance idPerformance="30" idEmploye="10">
            <notePerformance>11</notePerformance>
            <datePerformance>2022-12-10</datePerformance>
        </performance>
        <performance idPerformance="31" idEmploye="11">
            <notePerformance>15</notePerformance>
            <datePerformance>2022-12-11</datePerformance>
        </performance>
        <performance idPerformance="32" idEmploye="12">
            <notePerformance>14</notePerformance>
            <datePerformance>2022-12-12</datePerformance>
        </performance>
    </performances>

    <absences>
        <absence idAbence="1" idEmploye="1">
            <motifAbsence>Congé annuel</motifAbsence>
            <nombreDeJours>5</nombreDeJours>
            <dateAbsence>2021-05-10</dateAbsence>
        </absence>
        <absence idAbence="2" idEmploye="2">
            <motifAbsence>Maladie</motifAbsence>
            <nombreDeJours>2</nombreDeJours>
            <dateAbsence>2021-02-15</dateAbsence>
        </absence>
        <absence idAbence="3" idEmploye="6">
            <motifAbsence>Congé sans solde</motifAbsence>
            <nombreDeJours>15</nombreDeJours>
            <dateAbsence>2022-07-10</dateAbsence>
        </absence>
        <absence idAbence="4" idEmploye="7">
            <motifAbsence>Congé maladie enfant</motifAbsence>
            <nombreDeJours>3</nombreDeJours>
            <dateAbsence>2021-11-12</dateAbsence>
        </absence>
        <absence idAbence="8" idEmploye="8">
            <motifAbsence>Congé maternité</motifAbsence>
            <nombreDeJours>90</nombreDeJours>
            <dateAbsence>2021-09-05</dateAbsence>
        </absence>
        <absence idAbence="5" idEmploye="3">
            <motifAbsence>Formation</motifAbsence>
            <nombreDeJours>2</nombreDeJours>
            <dateAbsence>2021-10-20</dateAbsence>
        </absence>
        <absence idAbence="6" idEmploye="10">
            <motifAbsence>Congé annuel</motifAbsence>
            <nombreDeJours>8</nombreDeJours>
            <dateAbsence>2021-10-01</dateAbsence>
        </absence>
        <absence idAbence="7" idEmploye="7">
            <motifAbsence>Formation</motifAbsence>
            <nombreDeJours>6</nombreDeJours>
            <dateAbsence>2022-12-20</dateAbsence>
        </absence>
    </absences>
</chine>