<!DOCTYPE chine [
        <!ELEMENT chine (employes, postes, contratsDureeIndeterminee, departements, formations, seFormes, performances, absences)>
        <!ELEMENT employes (employe+)>
        <!ELEMENT employe (nom, prenom, telephone, adresse, dateDeNaissance, diplome)>
        <!ATTLIST  employe  idEmploye ID #REQUIRED
                            idDepartement IDREF #REQUIRED
                            idPoste IDREF #REQUIRED>
        <!ELEMENT nom (#PCDATA)>
        <!ELEMENT prenom (#PCDATA)>
        <!ELEMENT telephone (#PCDATA)>
        <!ELEMENT adresse (#PCDATA)>
        <!ELEMENT dateDeNaissance (#PCDATA)>
        <!ELEMENT diplome (#PCDATA)>

        <!ELEMENT postes (poste+)>
        <!ELEMENT poste (libelle, nombreHeuresParSemaine, occupation, salaireBase)>
        <!ATTLIST poste idPoste ID #REQUIRED>
        <!ELEMENT libelle (#PCDATA)>
        <!ELEMENT nombreHeuresParSemaine (#PCDATA)>
        <!ELEMENT occupation (#PCDATA)>
        <!ELEMENT salaireBase (#PCDATA)>

        <!ELEMENT contratsDureeIndeterminee (contrat+)>
        <!ELEMENT contrat (dateDebutContrat, numeroContrat, salaire)>
        <!ATTLIST   contrat idContrat ID #REQUIRED
                    idEmploye IDREF #REQUIRED>
        <!ELEMENT dateDebutContrat (#PCDATA)>
        <!ELEMENT numeroContrat (#PCDATA)>
        <!ELEMENT salaire (#PCDATA)>

        <!ELEMENT departements (departement+)>
        <!ELEMENT departement (nomDepartement, pays)>
        <!ATTLIST departement idDepartement ID #REQUIRED>
        <!ELEMENT nomDepartement (#PCDATA)>
        <!ELEMENT pays (#PCDATA)>

        <!ELEMENT formations (formation+)>
        <!ELEMENT formation (typeFormation, coutFormation)>
        <!ATTLIST formation idFormation ID #REQUIRED>
        <!ELEMENT typeFormation (#PCDATA)>
        <!ELEMENT coutFormation (#PCDATA)>

        <!ELEMENT seFormes (seForme+)>
        <!ELEMENT seForme (DateDebutFormation)>
        <!ATTLIST seForme   idSeForme ID #REQUIRED
                idFormation IDREF #REQUIRED
                idEmploye IDREF #REQUIRED>
        <!ELEMENT DateDebutFormation (#PCDATA)>

        <!ELEMENT performances (performance+)>
        <!ELEMENT performance (notePerformance, datePerformance)>
        <!ATTLIST   performance   idPerformance ID #REQUIRED
                    idEmploye IDREF #REQUIRED>
        <!ELEMENT notePerformance (#PCDATA)>
        <!ELEMENT datePerformance (#PCDATA)>

        <!ELEMENT absences (absence+)>
        <!ELEMENT absence (motifAbsence, nombreDeJours, dateAbsence)>
        <!ATTLIST absence    idAbsence ID #REQUIRED
                idEmploye IDREF #REQUIRED>
        <!ELEMENT motifAbsence (#PCDATA)>
        <!ELEMENT nombreDeJours (#PCDATA)>
        <!ELEMENT dateAbsence (#PCDATA)>
        ]>
<chine >
    <employes>
        <employe idEmploye="e1" idPoste="p16" idDepartement="d1">
            <nom>Zhang</nom>
            <prenom>Wei</prenom>
            <telephone>1234567890</telephone>
            <adresse>123 rue du Bonheur, Shanghai</adresse>
            <dateDeNaissance>1990-01-01</dateDeNaissance>
            <diplome>Master</diplome>
        </employe>
    </employes>
    <postes>
        <poste  idPoste="p16">
            <libelle>Comptable</libelle>
            <nombreHeuresParSemaine>35</nombreHeuresParSemaine>
            <occupation>true</occupation>
            <salaireBase>2500</salaireBase>
        </poste>
    </postes>
    <contratsDureeIndeterminee>
        <contrat idContrat="c1" idEmploye="e1">
            <dateDebutContrat>2021-01-01</dateDebutContrat>
            <numeroContrat>12001</numeroContrat>
            <salaire>3575</salaire>
        </contrat>
    </contratsDureeIndeterminee>
    <departements>
        <departement idDepartement="d1" >
            <nomDepartement>Ventes et marketing</nomDepartement>
            <pays>Chine</pays>
        </departement>
    </departements>

    <formations>
        <formation idFormation="f11">
            <typeFormation>Formation en vente et négociation</typeFormation>
            <coutFormation>1000</coutFormation>
        </formation>
    </formations>
    <seFormes>
        <seForme idSeForme="sf1"  idFormation="f11" idEmploye="e1">
            <DateDebutFormation>2022-12-20</DateDebutFormation>
        </seForme>

    </seFormes>
    <performances>
        <performance idPerformance="p1" idEmploye="e1">

            <notePerformance>12</notePerformance>
            <datePerformance>2021-12-01</datePerformance>

        </performance>
    </performances>
    <absences>
        <absence idAbsence="a1"  idEmploye="e1" >

            <motifAbsence>Congé annuel</motifAbsence>
            <nombreDeJours>5</nombreDeJours>
            <dateAbsence>2021-05-10</dateAbsence>

        </absence>
    </absences>
</chine>